// This file is generated by npm run codegen. Do not edit by hand.
export const ROLE = [
  "admin",
  "reviewer",
  "forecaster",
  "viewer"
] as const

export const ACCUM_HOURS = [
  24,
  48,
  168
] as const

export const WINDOW_STATUS = [
  "pending",
  "available",
  "partial",
  "invalid",
  "archived"
] as const

export const QC_STATUS = [
  "unchecked",
  "pass",
  "warn",
  "fail"
] as const

export const VERSION_STATUS = [
  "original",
  "draft",
  "submitted",
  "approved",
  "rejected",
  "released",
  "superseded"
] as const

export const SESSION_STATUS = [
  "editing",
  "saved",
  "discarded",
  "expired"
] as const

export const RELEASE_STATUS = [
  "active",
  "superseded"
] as const

export const PLOT_STATUS = [
  "pending",
  "running",
  "success",
  "partial_success",
  "failed",
  "permanently_failed"
] as const

export const SCAN_TYPE = [
  "manual",
  "scheduled",
  "startup"
] as const

export const PTYPE = [
  0,
  1,
  2,
  3
] as const

export const EDIT_TOOL = [
  "polygon",
  "line_buffer",
  "brush_path"
] as const

export const EDIT_VARIABLE = [
  "qpf",
  "ptype"
] as const

export const EDIT_OPERATION = [
  "set_value",
  "increase",
  "decrease",
  "multiply",
  "clear",
  "set_ptype",
  "screen_clear"
] as const

export const MASK_TYPE = [
  "polygon",
  "line_buffer",
  "brush_path"
] as const

export const REVIEW_ACTION = [
  "approve",
  "reject"
] as const

export const MISSING_REASON = [
  "file_not_found",
  "read_error",
  "dimension_mismatch"
] as const

export const ENUMS = {
  "role": ROLE,
  "accum_hours": ACCUM_HOURS,
  "window_status": WINDOW_STATUS,
  "qc_status": QC_STATUS,
  "version_status": VERSION_STATUS,
  "session_status": SESSION_STATUS,
  "release_status": RELEASE_STATUS,
  "plot_status": PLOT_STATUS,
  "scan_type": SCAN_TYPE,
  "ptype": PTYPE,
  "edit_tool": EDIT_TOOL,
  "edit_variable": EDIT_VARIABLE,
  "edit_operation": EDIT_OPERATION,
  "mask_type": MASK_TYPE,
  "review_action": REVIEW_ACTION,
  "missing_reason": MISSING_REASON,
} as const

export type Role = (typeof ROLE)[number]
export type AccumHours = (typeof ACCUM_HOURS)[number]
export type WindowStatus = (typeof WINDOW_STATUS)[number]
export type QcStatus = (typeof QC_STATUS)[number]
export type VersionStatus = (typeof VERSION_STATUS)[number]
export type SessionStatus = (typeof SESSION_STATUS)[number]
export type ReleaseStatus = (typeof RELEASE_STATUS)[number]
export type PlotStatus = (typeof PLOT_STATUS)[number]
export type ScanType = (typeof SCAN_TYPE)[number]
export type Ptype = (typeof PTYPE)[number]
export type EditTool = (typeof EDIT_TOOL)[number]
export type EditVariable = (typeof EDIT_VARIABLE)[number]
export type EditOperation = (typeof EDIT_OPERATION)[number]
export type MaskType = (typeof MASK_TYPE)[number]
export type ReviewAction = (typeof REVIEW_ACTION)[number]
export type MissingReason = (typeof MISSING_REASON)[number]
