import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const repoRoot = resolve(__dirname, '..', '..')
const frontendRoot = resolve(__dirname, '..')

function readJson(path) {
  return JSON.parse(readFileSync(path, 'utf8'))
}

function writeGeneratedFile(relativePath, content) {
  const target = resolve(frontendRoot, relativePath)
  mkdirSync(dirname(target), { recursive: true })
  writeFileSync(target, `${content.trimEnd()}\n`)
}

function quote(value) {
  return JSON.stringify(value)
}

const errorCodes = readJson(resolve(repoRoot, 'schemas', 'error_codes.json'))
const enums = readJson(resolve(repoRoot, 'schemas', 'enums.json'))

const flatErrorCodes = Object.values(errorCodes).flat()

writeGeneratedFile(
  'src/types/errorCodes.ts',
  `// This file is generated by npm run codegen. Do not edit by hand.
export const ERROR_CODE_GROUPS = ${JSON.stringify(errorCodes, null, 2)} as const

export const ERROR_CODES = ${JSON.stringify(flatErrorCodes, null, 2)} as const

export type ErrorCode = (typeof ERROR_CODES)[number]
export type ErrorCodeGroup = keyof typeof ERROR_CODE_GROUPS
`,
)

const enumEntries = Object.entries(enums)
const enumConstants = enumEntries
  .map(
    ([key, values]) =>
      `export const ${key.toUpperCase()} = ${JSON.stringify(values, null, 2)} as const`,
  )
  .join('\n\n')
const enumTypes = enumEntries
  .map(([key]) => {
    const typeName = key
      .split('_')
      .map((part) => `${part.charAt(0).toUpperCase()}${part.slice(1)}`)
      .join('')
    return `export type ${typeName} = (typeof ${key.toUpperCase()})[number]`
  })
  .join('\n')

writeGeneratedFile(
  'src/types/enums.ts',
  `// This file is generated by npm run codegen. Do not edit by hand.
${enumConstants}

export const ENUMS = {
${enumEntries.map(([key]) => `  ${quote(key)}: ${key.toUpperCase()},`).join('\n')}
} as const

${enumTypes}
`,
)
