spring:
  datasource:
    dynamic:
      primary: smdb
      strict: false
      datasource:
        stdb:
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://117.50.8.108:54329/postgres?sslmode=disable
          username: postgres
          password: Password123@postgres
          type: com.alibaba.druid.pool.DruidDataSource
        smdb:
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://117.50.8.108:54329/postgres?sslmode=disable
          username: postgres
          password: Password123@postgres
          type: com.alibaba.druid.pool.DruidDataSource
        fidb:
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://117.50.8.108:54329/postgres?sslmode=disable
          username: postgres
          password: Password123@postgres
          type: com.alibaba.druid.pool.DruidDataSource
  ## 数据连接池
  druid:
    initialSize: 1
    minIdle: 1
    maxActive: 50
    keepAlive: true
    maxWait: 60000
    minEvictableIdleTimeMills: 300000
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: true
    poolPreparedStatements: true
    ## 配置拦截
    filters: stat,wall

# mybatis 配置信息xiang
mybatis-plus:
  # 配置mapper.xml文件路径
  mapper-locations:
    - classpath:/mapper/**/*.xml
    - classpath:/mapper/forecast/*.xml
#  configuration:
#    # 开启log
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

