at=2
atmax=2
atmin=2
slp=1
rh=1
wd=1
ws=1
vis=1
lcc=1
n=1
lonlat=70,50,111,25
lon_dis=0.05
lat_dis=0.05
ecmf=total_precipitation_surface,visibility_surface
grapes=total_precipitation_surface_$_hour_accumulation
kt=var123-0-2-134_height_above_ground
swc9km=total_precipitation_surface_$_hour_accumulation
swc3km=total_precipitation_surface_$_hour_accumulation
test=0
excel_upload=/data/upload/
ecmf_upload=/data/upload/
#ecmf_upload=/data/upload/
grapes_upload=/data/upload/
kt_upload=/data/upload/
swc9km_upload=/data/upload/
swc3km_upload=/data/upload/
t1279_upload=/data/upload/
cldas_upload=/data/upload/
scmoc_upload=/data/upload/
cmpa_upload=/data/upload/
default_upload=/data/upload/
ecmf_back=/data/back/
grapes_back=/data/upload/
kt_back=/data/upload/
swc9km_back=/data/upload/
swc3km_back=/data/upload/
t1279_back=/data/upload/
cldas_back=/data/upload/
scmoc_back=/data/upload/
cmpa_back=/data/upload/
ecmf_source=/data/upload/
grapes_source=/data/upload/
kt_source=/data/upload/
swc9km_source=/data/upload/
swc3km_source=/data/upload/
t1279_source=/data/upload/
cldas_source=/data/upload/
scmoc_source=/data/upload/
cmpa_source=/data/upload/
custom_images=/data/images/
cmb_image_file_path=/data/images/line_new.png
upgrade_station_model_url=http://192.168.2.81:8035/upgradeModel
upgrade_station_model_fix=30
upgrade_grib_model_url=http://192.168.2.80:8081/run
upgrade_grib_model_fix=30
replace_station_model_url=http://192.168.2.81:8035/replaceModel
plot_image_url=http://192.168.2.81:7022/plotImage
check_station_url=http://192.168.2.81:7088/cdsz/check/checkStationDataDayIndb
ecmf_path=/cloud/share-files/SC/nafp/ecmwf/hres/
grapes_path=/cloud/share-files/SC/nafp/cma/grapes/
ecmf_his_path=/cloud/nas/rsync/ecmwf/
grapes_his_path=/cloud/nas/rsync/grapes/
ecmf_his_cut_path=/cloud/nas/rsync/ecmwf_cut/
grapes_his_cut_path=/cloud/nas/rsync/grapes_cut/
swc9km_his_path=/cloud/nas/rsync/swc9km/
cldas_his_path=/cloud/nas/rsync/cldas/
ecmf_model_txt=/data/revised-data/nets/kalmanfilter/ecmwf/
grapes_model_txt=/data/revised-data/nets/kalmanfilter/grapes/
deep_model_txt=/data/revised-data/nets/deeplearning/
ecmf_ptype_txt=/data/revised-data/nets/statistics/ptype_kalmanfilter/ecmwf/
grapes_ptype_txt=/data/revised-data/nets/statistics/ptype_kalmanfilter/grapes/
deep_ptype_txt=/data/revised-data/nets/statistics/ptype_deeplearning/