wait=5000
ecmf_u=_u_
ecmf_v=_v_
cldas_u=u-
cldas_v=v-
grapes_u=u-
grapes_v=v-
kt_u=u-
kt_v=v-
swc9km_u=u-
swc9km_v=v-
swc3km_u=u-
swc3km_v=v-
ecmf_around=1
grapes_around=1
swc9km_around=1
swc3km_around=1
cldas_around=1
t1279_around=1
ecmf_rain=total_column_water_surface
grapes_rain=total_precipitation_surface_$_hour_accumulation
swc9km_rain=total_precipitation_surface_$_hour_accumulation
swc3km_csv=/data/extracted-data/history/stations/swc3km/
swc3km_txt=/data/extracted-data/history/nets/swc3km/
swc9km_csv=/data/extracted-data/history/stations/swc9km/
swc9km_txt=/data/extracted-data/history/nets/swc9km/
#grapes_csv=/data/extracted-data/history/stations/grapes/
#grapes_txt=/data/extracted-data/history/nets/grapes/
#ecmf_csv=/data/extracted-data/history/stations/ecmwf/
#ecmf_txt=/data/extracted-data/history/nets/ecmwf/
grapes_csv=/data/extracted-data/history/stations/grapes_0507/
grapes_txt=/data/extracted-data/history/nets/grapes_0507/
ecmf_csv=/data/extracted-data/history/stations/ecmwf_0507/
ecmf_txt=/data/extracted-data/history/nets/ecmwf_0507/
cmpa_csv=/data/extracted-data/history/stations/cmpa/
cmpa_txt=/data/extracted-data/history/nets/cmpa/
scmoc_txt=/data/extracted-data/history/nets/scmoc/
era5_csv=/data/extracted-data/history/stations/era5/
era5_txt=/data/extracted-data/history/stations/era5/
t1279_txt=/data/extracted-data/history/nets/zc1279/
kt_txt=/data/extracted-data/history/nets/kt1279/
cldas_txt=/data/extracted-data/history/nets/cldas/
#swc9km_txt=/data/extracted-data/history/nets/swc9km/
#swc3km_csv=/data/extracted-data/test/stations/swc3km/
#swc9km_csv=/data/extracted-data/test/stations/swc9km/
#grapes_csv=/data/extracted-data/test/stations/grapes/
#grapes_txt=/data/extracted-data/test/nets/grapes/
#ecmf_csv=/data/extracted-data/test/stations/ecmwf/
#ecmf_txt=/data/extracted-data/test/nets/ecmwf/
#cmpa_csv=/data/extracted-data/test/stations/cmpa/
#cmpa_txt=/data/extracted-data/test/nets/cmpa/
#scmoc_txt=/data/extracted-data/test/nets/scmoc/
#era5_csv=/data/extracted-data/test/stations/era5/
#era5_txt=/data/extracted-data/test/nets/era5/
#t1279_txt=/data/extracted-data/test/nets/zc1279/
#kt_txt=/data/extracted-data/test/nets/kt1279/
#cldas_txt=/data/extracted-data/test/nets/cldas/
t1279_job_txt=/data/history-files/yyyh/out/
#t1279_csv=E:\fl\datas\out
#t1279_job_txt=E:\fl\datas\out
t1279_csv=/data/history-files/yyyh/out/
ecmf_job_txt=/data/history-files/yyyh/out/
grapes_job_txt=/data/history-files/yyyh/out/
#
ecmf_model_txt=/data/revised-data/nets/kalmanfilter/ecmwf/
grapes_model_txt=/data/revised-data/nets/kalmanfilter/grapes/
deep_model_txt=/data/revised-data/nets/deeplearning/
ecmf_ptype_txt=/data/revised-data/nets/statistics/ptype_kalmanfilter/ecmwf/
grapes_ptype_txt=/data/revised-data/nets/statistics/ptype_kalmanfilter/grapes/
deep_ptype_txt=/data/revised-data/nets/statistics/ptype_deeplearning/
#ecmf_model_txt=E:/fl/datas/rain_png/kalmanfilter/ecmwf/
#grapes_model_txt=E:/fl/datas/rain_png/kalmanfilter/grapes/
#deep_model_txt=E:/fl/datas/rain_png/deeplearning/
#ecmf_ptype_txt=E:/fl/datas/rain_png/statistics/ptype_kalmanfilter/ecmwf/
#grapes_ptype_txt=E:/fl/datas/rain_png/statistics/ptype_kalmanfilter/grapes/
#deep_ptype_txt=E:/fl/datas/rain_png/statistics/ptype_deeplearning/
#startLon,startLat,endLon,endLat
lonlat=70, 50, 111, 25
lon_dis=0.05
lat_dis=0.05
history=1
t1279_rain3_press=999
t1279_t2_press=999
t1279_td2_press=999
t1279_wind10_press=999
t1279_wind_press=20,250,300,400,500,700,850,925
t1279_temper_press=500,600,700,850
t1279_height_press=500,600,700,850
t1279_rh_press=500,600,700,850
kt_TT_press=500,600,700,850
kt_RH_press=500,600,700,850
kt_HH_press=500,600,700,850
#prcp,pair,wind,qair,tair
ecmf_lon_step=0.1
ecmf_lat_step=0.1
grapes_lon_step=0.1
grapes_lat_step=0.1
t1279_lon_step=0.1
t1279_lat_step=0.1
swc9km_lon_step=0.1
swc9km_lat_step=0.1
cldas_lon_step=0.1
cldas_lat_step=0.1
ecmf_file_min_size=209715200
grapes_file_min_size=104857600
swc9km_file_min_size=7100000
swc3km_file_min_size=100000
cmpa_file_min_size=1048576
t1279_file_min_size=204800
kt_file_min_size=10240
cldas_file_min_size=102400
scmoc_file_min_size=209715200
custom_images=/data/images/
#custom_images=E:/fl/datas/rain_png/
server_ip=localhost
server_port=8889
server_http=http://localhost:8889/
public.surf_fc_tab=station,datatime,validdate
public.deep_grib_rain_tab=filename,datatime,vti
public.deep_grib_rain_value_tab=station,datatime,vti
public.ecmf_grib_rain_tab=filename,datatime,vti
public.ecmf_grib_rain_value_tab=station,datatime,vti
public.grapes_grib_rain_tab=filename,datatime,vti
public.grapes_grib_rain_value_tab=station,datatime,vti
public.nafp_cldas_value_tab=station,datatime
public.nafp_grib_tab=filename,validdate,vti,datatype
public.surf_chn_mul_hor_micaps=datetime,station_id_d
public.extract_data_record_tab=station,datasource,filepath
public.nafp_ecmf_value_tab=station,datatime,vti
public.nafp_grapes_value_tab=station,datatime,vti
station_path=/data/revised-data/stations/
#station_path=E:/fl/datas/station/
deep_path=/data/revised-data/nets/deeplearning/
deep_head=tp_999_deeplearning_
ecmf_path=/data/revised-data/nets/kalmanfilter/ecmwf/
ecmf_head=tp_999_ecmf_
grapes_path=/data/revised-data/nets/kalmanfilter/grapes/
grapes_head=tp_999_grapes_
micaps_path=/data/extracted-data/oper/stations/mdfs/
fy4b_path=/data/extracted-data/oper/stations/fy4b/