all_datamanager=public.nafp_grib_tab
kt_datamanager=public.nafp_grib_tab
ecmf_datamanager=public.nafp_grib_tab
grapes_datamanager=public.nafp_grib_tab
swc9km_datamanager=public.nafp_grib_tab
cldas_datamanager=public.nafp_grib_tab
cmpa_datamanager=public.nafp_grib_tab
station=public.surf_fc_tab
kt=public.nafp_kt1279_tab
t1279=public.nafp_t1279_tab
ecmf=public.nafp_ecmf_tab
grapes=public.nafp_grapes_tab
swc9km=public.nafp_swc9km_tab
cldas=public.surf_chn_mul_hor_micaps
cldas_p5=public.surf_chn_mul_hor_micaps
cmpa=public.nafp_cmpa_tab
scmoc=public.nafp_scmoc_tab
swc3km=public.nafp_swc3km_tab
t1279_value=public.nafp_t1279_value_tab
ecmf_value=public.nafp_ecmf_value_tab
deep_value=public.nafp_deep_value_tab
grapes_value=public.nafp_grapes_value_tab
swc9km_value=public.nafp_swc9km_value_tab
ecmf_rain=public.ecmf_grib_rain_tab
grapes_rain=public.grapes_grib_rain_tab
deep_rain=public.deep_grib_rain_tab
ecmf_rain_value=public.ecmf_grib_rain_value_tab
grapes_rain_value=public.grapes_grib_rain_value_tab
deep_rain_value=public.deep_grib_rain_value_tab
#nafp_ecmf_value=public.nafp_ecmf_value_tab
#nafp_grapes_value=public.nafp_grapes_value_tab
#nafp_deep_value=public.nafp_deep_value_tab
#nafp_swc9km_value=public.nafp_swc9km_value_tab
station=public.surf_fc_tab
micaps=public.surf_chn_mul_hor_micaps
fy4b=public.surf_chn_mul_hor_micaps