#rdb.driverClassName=org.postgresql.Driver
#rdb.url=jdbc:postgresql://192.168.2.81:5432/szyb?sslmode=disable
#rdb.username=yyyh
#rdb.password=yyyh@2025
#rdb.ip=192.168.2.81
#rdb.port=5432
#rdb.type=postgres
#rdb.driverClassName=org.postgresql.Driver
#rdb.url=jdbc:postgresql://192.168.3.4:5432/xbzq?sslmode=disable
#rdb.username=xbzq001
#rdb.password=123456@qwer
#rdb.ip=192.168.3.4
#rdb.port=5432
#rdb.type=postgres
rdb.driverClassName=org.postgresql.Driver
rdb.url=jdbc:postgresql://192.168.3.4:5432/xbzq?sslmode=disable
rdb.username=xbzq001
rdb.password=123456@qwer
rdb.ip=192.168.3.4
rdb.port=5432
rdb.type=postgres
odb.driverClassName=org.postgresql.Driver
odb.url=jdbc:postgresql://117.50.8.108:54329/postgres?sslmode=disable
odb.username=postgres
odb.password=Password123@postgres
odb.ip=192.168.2.81
odb.port=5432
odb.type=postgres