2_metre_temperature_surface=t2
2_metre_dewpoint_temperature_surface=d2
10_metre_u_wind_component_surface=ws10,wd10,wind10
total_precipitation_surface=pr
total_precipitation_surface_rain=tp
visibility_surface=vis
total_column_water_vapour_surface=tcwv
total_column_water_surface=tcw
surface_pressure_surface=psfc
specific_humidity_isobaric=q
geopotential_height_isobaric=gh
relative_humidity_isobaric=rh
temperature_isobaric=t
total_cloud_cover_surface=tcc
low_cloud_cover_surface=lcc
t2m=t2