ecmf=2_metre_temperature_surface,total_precipitation_surface,visibility_surface,total_cloud_cover_surface,low_cloud_cover_surface
ecmfnc=t2m
#ecmf=10_metre_u_wind_component_surface
ecmf@uv=10_metre_u_wind_component_surface
grapes=temperature_height_above_ground,total_precipitation_surface_$_hour_accumulation,visibility_surface,total_cloud_cover_surface_layer,low_cloud_cover_surface_layer
grapes@uv=u-component_of_wind_height_above_ground
#temperature_surface,dewpoint_temperature_height_above_ground,total_precipitation_surface_$_hour_accumulation,precipitation_type_surface
kt=relative_humidity_isobaric,var123-0-2-134_height_above_ground
kt@uv=u-component_of_wind_isobaric
#swc9km=total_precipitation_surface_$_hour_accumulation
swc9km=temperature_surface,visibility_surface,total_precipitation_surface_$_hour_accumulation,total_cloud_cover_entire_atmosphere,low_cloud_cover_lcy
swc9km@uv=u-component_of_wind_height_above_ground
swc3km=visibility_surface,temperature_height_above_ground,total_precipitation_surface_$_hour_accumulation,low_cloud_cover_low_cloud,total_cloud_cover_entire_atmosphere_single_layer
#swc3km=temperature_height_above_ground
swc3km@uv=u-component_of_wind_height_above_ground
era5=precipitation_type_surface,total_cloud_cover_surface,low_cloud_cover_surface
cldas=tair,wind,prcp
cldas@uv=u-component_of_wind_height_above_ground