temperature_height_above_ground=t2
dewpoint_temperature_height_above_ground=d2
u-component_of_wind_height_above_ground=ws10,wd10,wind10
total_precipitation_surface_$_hour_accumulation=pr
total_precipitation_surface_$_hour_accumulation_rain=tp
precipitation_type_surface=ptype
visibility_surface=vis
total_cloud_cover_surface_layer=tcc
low_cloud_cover_surface_layer=lcc
specific_humidity_height_above_ground=sh2
specific_humidity_isobaric=q
pressure_surface=psfc
relative_humidity_height_above_ground=rh2
temperature_isobaric=t
relative_humidity_isobaric=rh
geopotential_height_isobaric=gh