datetime=datetime
station_id_d=station_id_d
station_name=station_name
province=province
lat=lat
lon=lon
alti=alti
prs_sea=prs_sea
tem=tem
tmax_24h=tem_max_24h
tmin_24h=tem_min_24h
dpt=dpt
rhu=rhu
pre_1h =pre_1h
pre=pre
win_d_avg_10mi=win_d_avg_10mi
win_s_avg_10mi=win_s_avg_10mi
win_d_inst=win_d_inst
win_s_inst=win_s_inst
vis=vis
tp=pre_24h
filename=filename
filepath=filepath
inserttime=inserttime