station=station
rain=rain
filename=filename
dataTime=datatime
hour=hour
vti=vti
rainvti=rainvti
datatype=datatype
sourcepath=sourcepath
filepath=filepath
inserttime=inserttime
filesize=filesize
filetype=filetype
validdate=validdate
datasource=datasource
urlpath=urlpath