station=station
lon=lon
lat=lat
analDate=datatime
validDate=validDate
vti=vti
year=year
month=month
day=day
hour=hour
t2=at
rh=rh
wd10=wd
ws10=ws
slp=slp
vis=vis
n=n
lcc=lcc
tcc=n
pr=rain
#rain=rain
filename=filename
filepath=filepath
inserttime=inserttime
tp=rain24
tmax_24h=at_max
tmin_24h=at_min
ptype=ptype