temperature_surface=t2
visibility_surface=vis
u-component_of_wind_height_above_ground=ws10,wd10,wind10
total_precipitation_surface_$_hour_accumulation=pr
total_precipitation_surface_$_hour_accumulation_rain=tp
total_cloud_cover_entire_atmosphere=tcc
low_cloud_cover_lcy=lcc